version: '3.8'
services:

  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-build-stage
    ports:
      - 3000:3000

volumes:
  postgres: